server:
  port: 8190
  servlet:
    context-path: /store-carts
integrations:
  product-service:
    url: http://localhost:8189/store-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
cart-service:
  cart-prefix: store_cart_
