#server:
#  port: 8189
#  servlet:
#    context-path: /store-core
spring:
  flyway:
    locations: classpath:/db/test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-mydatabase;MODE=MYSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
